### ISSUE TITLE
该爬虫不会被封ip么？

### ISSUE THREAD

**Issue by SnakeHacker** [jinfagang/weibo_terminater#1]
如题

**Comment by jinfagang** [comment]
Yes, it will be, but later I will add some strategy such as multi account solving and period crawl with uncontinues, currently you can manually change cookies if it being baned.

**Comment by buaanie** [comment]
据我说知，新浪的策略是ip肯定会封，建议先考虑ip代理池的实现

**Comment by jinfagang** [comment]
Of course, most domestic websites will banned crawlers, if we don't have a lot of dynamic ips, then should do something strategy avoid this, currently this is what this project exactly do, we implement various algorithm and dispatch strategy to do this, such as multi account processing, delay camouflage and so on, but as you can see, we can not get this problem done easily even you have dynamic ips. Luckily, this is **what this project meanings**: we launch lots of people contribute togther to get our job done!
