### ISSUE TITLE
感觉判断cookie那里的逻辑有一些问题

### ISSUE THREAD

**Issue by ResolveWang** [jinfagang/weibo_terminater#11]
你好，我大概读完了该项目的源码，在运行test的时候，发现`get_cookie_from_network`这个函数好像有一些问题，只有当`if cookies_dict[account_id] is not None`才会去更新或者cookie.试想一下，如果我第一次模拟登陆失败了，返回的cookie是None，存到了cookies文件中，那么以后我用该账号再登陆的话，该账号的cookie永远就写不进去了，因为它一直为None.不知道我的想法是否正确

**Comment by jinfagang** [comment]
Cookies if not get will not save into local.
