### ISSUE TITLE
win10 64位系统运行时提示无法找到PhantomJS 

### ISSUE THREAD

**Issue by danjx** [jinfagang/weibo_terminater#12]
python版本是3.5.2。这样的错误提示：can not find PhantomJS driver, please download from http://phantomjs.org/download.html based on your system.
可是我已经下载安装过了，而且在path里也添加了phantomjs目录。在命令行里直接运行 phantomjs也能正常运行。

**Comment by jinfagang** [comment]
You should set PhantomJS installed path in settings/config.py file, I have leave some instruction there, just follow it.

**Comment by danjx** [comment]
谢谢，我找到了。现在可以运行了。
