### ISSUE TITLE
无法模拟登录了吗？

### ISSUE THREAD

**Issue by danjx** [jinfagang/weibo_terminater#13]
终于配置好可以跑通了，只是登录的时候好像失败了。
  File "D:\weibo_terminater-master\core\dispatch_center.py", line 50, in execute
error, account id 18991158502 is not valid, pass this account, you can edit it and then update cookies. 
然后我通过https://passport.weibo.cn/signin/login 这个地址试着登录了一下，发现需要手工画一个登录确认的图标，就是按照箭头拖动鼠标。晕了，微博刚刚加上这个功能吗？

**Comment by jinfagang** [comment]
No way, is there an verification code or something else? This could make things hard. I haven't check that, could u give us more detail or screen shot about this issue?

**Comment by danjx** [comment]
我刚才试了一下，现在成功登录了。看来是微博随机验证的。我用chrome试着手工登录的时候，输入完用户名和密码成功后出来个九宫格，九宫格每个圆圈里是箭头，微博系统让我顺着箭头方向拖动，拖动成功后就登录了。
