### ISSUE TITLE
可以读取微博内容，但是最后无法保存

### ISSUE THREAD

**Issue by danjx** [jinfagang/weibo_terminater#14]
通过PyCharm运行，可以看到已经读取到微博内容了。但是最后保存内容的时候报错：
[WinError 183] 当文件已存在时，无法创建该文件。: './weibo_detail'
current account being banned, return to dispatch center, resign for new account..
scrap not finish, account resource run out. update account move on scrap.
我觉得是不是应该第一步就保存读到的微博内容呢？读10页保存一次，下次就可以略过已经保存的内容只抓取新的内容。

**Comment by jinfagang** [comment]
You are right, I will update save strategy in next version.

**Comment by ponngzhao** [comment]
将根 ./weibo_detail 文件夹改成其他名称或者删除，可以解决这个错误

**Comment by luisxxx** [comment]
您好，我把./weibo_detail文件夹删掉了，这个错误确实不报了。但是保存的文件是空的。
