### ISSUE TITLE
 'Dispatcher' object has no attribute 'all_accounts'

### ISSUE THREAD

**Issue by wczqhd** [jinfagang/weibo_terminater#16]
运行报错“ 'Dispatcher' object has no attribute 'all_accounts'”
看了运行结果，提示“[Errno 2] No such file or directory: 'settings/cookies.pkl'”，是不是因为没有cookies.pkl文件导致出错“'Dispatcher' object has no attribute 'all_accounts'”

**Comment by jinfagang** [comment]
You maybe haven't get cookies success, you should see get cookies successfully, if not, that must cause by account issue which you can set your account inside settings/account.py.

**Comment by wczqhd** [comment]
hm..................but you know, Weibo has combined our id with our mobile number,,,,,if I try it with my own id,,,may it will be baned  shortly.   So ,pls give me some suggestion on how to get more usable  id? :)

**Comment by jinfagang** [comment]
Baned will be release 2 hours later, not defend your normal use.

**Comment by levenls** [comment]
I have got the same issue. All the accounts failed to dump cookies.pkl (total 5), but i can login in with these accounts manually.

**Comment by levenls** [comment]
it turns out weibo has a validate process before login in m.weibo.cn/signin/login page.

**Comment by jinfagang** [comment]
@levenls I don't know what happen with your accounts, I fully tested my 3 accounts, all can normally get cookies, except I tested util being banned, if banned, can not get cookies anymore, or login successfully, only way is to waite for about 2-3 hours for release.
