### ISSUE TITLE
百度网盘？你们疯了么！

### ISSUE THREAD

**Issue by LyZane** [jinfagang/weibo_terminater#17]
> 对全部微博进行爬取，然后把结果上传到我们内部的 **百度云网盘**

就说一条：百度网盘存在封号后申述无门的现象。

**Comment by jinfagang** [comment]
To care most of people behind the wall, but dropbox maybe a better way, however this should not be care about, I have many tunnels to make data savely.

**Comment by LyZane** [comment]
@jinfagang  了解
