### ISSUE TITLE
请问weibo_id.list文件在哪里

### ISSUE THREAD

**Issue by buaanie** [jinfagang/weibo_terminater#18]
看介绍说整理了800W个分类账号在weibo_id.list这个文件中，但是并没有找到相关文件。

**Comment by jinfagang** [comment]
We have and group to discuss about this

**Comment by jiefangjun** [comment]
作者提交了分门别类的近800万用户id的list，全网开爬(Consider weibo official limitations, we can't distributed all list, just for sample, join our contributor team we will give every contributor single and unique part of id_file.)；
加入项目贡献，会分给你一段ID文件

**Comment by jinfagang** [comment]
Sorry about the ids file, consider of copyright issue, we currently not opensource this, we using distribution form to let everyone envolved.

**Comment by buaanie** [comment]
thanks a lot
