### ISSUE TITLE
./core/dispatch_center.py中的_init_single_mode()有逻辑错误

### ISSUE THREAD

**Issue by ponngzhao** [jinfagang/weibo_terminater#19]
`./core/dispatch_center.py`中的`_init_single_mode()`函数循环体中Line 96-99

`result = scraper.crawl()`
`if result:`
 `    print('finished!!!')`
 `    break`

会导致`./scraper/weibo_scraper.py`中，main函数的`wb.write_text()`不执行，导致存到txt中失败。

**Comment by jinfagang** [comment]
Thanks for bug report, If you can test your edited version and make it run in exactly way, you can send me a PR, I will merge that after fully tested.
