### ISSUE TITLE
考虑群策群力的话，是不是搞一个类似数据众筹的平台

### ISSUE THREAD

**Issue by CodePothunter** [jinfagang/weibo_terminater#2]
使用这个统一的爬虫，每人分配一批种子微博用户，从这些用户开始爬，爬完的结果再上传到平台。保持更新，供大家使用。

**Comment by jinfagang** [comment]
Good idea, I create an wechat group specific for NLP researcher or AI enthusiasts. Adding `jintianiloveu` I will envolved you in. As well as QQ group 263018023.

**Comment by redreamality** [comment]
brilliant，added you on wechat
