### ISSUE TITLE
使用遇到很多困难

### ISSUE THREAD

**Issue by zhengboss** [jinfagang/weibo_terminater#20]
错误信息：
`have not get cookies yet.
headers:  {'User-Agent': 'Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko/20100101 Firefox/11.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}
http://weibo.cn/u/1?filter=0&page=1
'WeiBoScraper' object has no attribute 'cookie'
-- getting user name
'WeiBoScraper' object has no attribute 'html'
html not properly loaded, maybe cookies out of date or account being banned. change an account please
`
本人不会python，想爬取新浪微博数据，能不能给我分享数据？联系方式531020008@qq.com
我做过一些java版本的爬虫，有新浪爱问的爬虫，还有大众点评等等。急需联系，谢谢合作

**Comment by ResolveWang** [comment]
你需要什么数据？我有微博用户的数据

**Comment by zhengboss** [comment]
后来我用java版本实现了新浪微博手机版爬虫，手机版的要简单很多。电脑版本的新浪微博登录要使用base64位加密，还有rsa加密。手机版的就不用了。

**Comment by ResolveWang** [comment]
这个项目也是抓的手机版啊。手机版能获取的信息不是很全，我实现的一个分布式的微博爬虫就是直接抓取的PC版，PC版的限制更多，并且需要解析的东西也多很多。

**Comment by zhengboss** [comment]
pc版我在知乎上看到过破解登录的过程，自己分析挺费劲的，pc版确实比较难。我用的java框架htmlunit，java版无界面浏览器，一律都在内存中分析和点击页面，但是也有一些缺陷。有些实现的不是特别理想。

**Comment by zhengboss** [comment]
新浪微博数据特别多，我也是刚刚开始干，这东西做好了，要分布式，并行爬取，断点续爬功能，线程池共享，而且有ip和账号限制，要使用动态ip去干，而且是一个长期的任务

**Comment by ResolveWang** [comment]
是的，我目前就是使用分布式的方式，就是感觉账号太少了。
