### ISSUE TITLE
i want to contribute this project

### ISSUE THREAD

**Issue by af1ynch** [jinfagang/weibo_terminater#25]
how can i get the ids

**Comment by orientez** [comment]
want to contribute +1. I want to add a module to get detailed information about fans.

**Comment by jinfagang** [comment]
Feel free to send PR!

**Comment by af1ynch** [comment]
can you hand out some ids?

**Comment by HuskyAlvarez** [comment]
What yew mean?
________________________________

**Comment by af1ynch** [comment]
The id_file in settings
