### ISSUE TITLE
modify suggest

### ISSUE THREAD

**Issue by scmsqhn** [jinfagang/weibo_terminater#27]
1 set a ip addrs for all the spider to check if this content is be checked
    ex. the spider can request xx.xx.xxx.xxx:80,to obtain a  name list which is be obatained
2 redis install the crawl status
    ex. save all the crawl msg into redis,to manage the weibo_id list is the key-point of project
3 "oray"(huashengge) can make the ip addrs easy

**Comment by jinfagang** [comment]
Thanks for this advice, I will update ip address dispath next version.
