### ISSUE TITLE
无法爬取数据

### ISSUE THREAD

**Issue by SiyaoZheng** [jinfagang/weibo_terminater#3]
添加了一个id后运行python main.py得到如下结果：
`[debug mode] crawling weibo from id 1669879400
setting cookies..
headers:  {'Connection': 'keep-alive', 'User-Agent': 'Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko/20100101 Firefox/11.0', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate'}
http://weibo.cn/u/1669879400?filter=0&page=1
success load html..
-- getting user name
list index out of range
html not properly loaded, maybe cookies out of date.`

**Comment by SiyaoZheng** [comment]
[debug mode] crawling weibo from id 1669879400
setting cookies..
headers:  {'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko/20100101 Firefox/11.0', 'Connection': 'keep-alive'}
http://weibo.cn/u/1669879400?filter=0&page=1
success load html..
-- getting user name
list index out of range
html not properly loaded, maybe cookies out of date.

**Comment by jinfagang** [comment]
this maybe cookies out of date or being baned by weibo, I will finish this anti-forbidden restriction later. Currently, you can crawl using multi account.
