### ISSUE TITLE
登陆遇到验证码问题，有人遇到过嘛

### ISSUE THREAD

**Issue by Z-Tracy** [jinfagang/weibo_terminater#32]
保持cookies的时候遇到登陆不了，后面用webdriver.chrome查看了下 发现遇到了验证码问题了。这个有程序有考虑过嘛？
![image](https://cloud.githubusercontent.com/assets/10585586/25840173/56edbfca-34cd-11e7-9a01-3bdc67a5e9ce.png)

**Comment by xiaochao** [comment]
我也遇到了，虽然登录成功了，但是获取到的cookie是空的，应该也是遇到验证码的问题了

**Comment by jinfagang** [comment]
Currently have no solution about this, mabe in next version I will improve this.
