### ISSUE TITLE
account.py里的id如何设置

### ISSUE THREAD

**Issue by xiaochao** [jinfagang/weibo_terminater#33]
我试了浏览器地址里的id，不行
我试了登录名，不行

error, account id ***** is not valid

**Comment by jinfagang** [comment]
account.py set your weibo account and password

**Comment by xiaochao** [comment]
我在account.py里面设置了，但是一直提示not valid， 我的机器在国外，是不是会有问题

**Comment by xiaochao** [comment]
我在页面上输入登录是正常的

**Comment by jinfagang** [comment]
May because of the delay, you can change the delay time waiting for PhantomJS load page fully.
