### ISSUE TITLE
settings/accounts.py文件里的账号设置

### ISSUE THREAD

**Issue by wight911** [jinfagang/weibo_terminater#37]
你好！
我用了一个自己的weibo小号测试，如以下 xxxxxx，xxxx 处。得到如下报错信息：

apple$ python3 main.py
[debug mode] crawling weibo from id realangelababy
preparing cookies for account {'password': 'xxxxxx', 'id': 'xxxx'}
loading PhantomJS from /Users/apple/phantomjs-2.1.1-macosx/bin/phantomjs
opening weibo login page, this is first done for prepare for cookies. be patience to waite load complete.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 40/40 [00:20<00:00,  1.99it/s]
Message: {"errorMessage":"Element is not currently interactable and may not be manipulated","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"170","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:56354","User-Agent":"Python http auth"},"httpVersion":"1.1","method":"POST","post":"{\"value\": [\"1\", \"3\", \"3\", \"1\", \"7\", \"3\", \"1\", \"6\", \"2\", \"8\", \"2\"], \"sessionId\": \"f48650a0-38c7-11e7-8cf6-7ba4e9053550\", \"text\": \"xxxx\", \"id\": \":wdc:1494781733275\"}","url":"/value","urlParsed":{"anchor":"","query":"","file":"value","directory":"/","path":"/value","relative":"/value","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/value","queryKey":{},"chunks":["value"]},"urlOriginal":"/session/f48650a0-38c7-11e7-8cf6-7ba4e9053550/element/:wdc:1494781733275/value"}}
Screenshot: available via screen

error, account id xxx is not valid, pass this account, you can edit it and then update cookies. 

all accounts getting cookies finished. starting scrap..
[Errno 2] No such file or directory: 'settings/cookies.pkl'
error, not find cookies file.
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    dispatcher.execute()
  File "/Users/apple/Documents/weibo_terminater/core/dispatch_center.py", line 50, in execute
    self._init_single_mode()
  File "/Users/apple/Documents/weibo_terminater/core/dispatch_center.py", line 93, in _init_single_mode
    scraper = WeiBoScraper(using_account=self.all_accounts[0], uuid=self.user_id, filter_flag=self.filter_flag)
AttributeError: 'Dispatcher' object has no attribute 'all_accounts'

是因为account.py中的account id设置不正确吗？试过各种情况，包括手机号、中文别名，以及http://weibo.com/xxxxxx/profile?topnav=1&wvr=6  中的 xxxxxx 数字串，都是上述类似的错误，不知这是什么情况？

谢谢！

**Comment by jinfagang** [comment]
就是登陆微博的账号和密码，不是网址的id，这个获取cookies就是模拟网页登陆获取

**Comment by wight911** [comment]
明白了，谢谢！
