### ISSUE TITLE
请问为什么会报can not find PhantomJS driver的错误

### ISSUE THREAD

**Issue by luisxxx** [jinfagang/weibo_terminater#39]
win10 64位
报错如图所示
感谢
![test](https://cloud.githubusercontent.com/assets/15872969/26133027/47b946d2-3a72-11e7-99b9-d647d924f300.jpg)

**Comment by jinfagang** [comment]
You should follow the usage instructions, PhantomJS must be installed for simulate login into weibo and get cookies.

**Comment by luisxxx** [comment]
Thanks. But before the **_python main.py_**, I had already installed PhantomJS and confirmed it to be installed well, as indicated in the figure above _**phantomjs --version**_.
I did not fix it.
Could you please further explain it?
Thank you.
