### ISSUE TITLE
WeiBoScraper对象中的_get_weibo_detail_comment()方法创建文件夹以及微博评论细节.txt的逻辑不太合适

### ISSUE THREAD

**Issue by zixuanweeei** [jinfagang/weibo_terminater#4]
weibo_scraper.py Line 186 - 188:
`        weibo_comments_save_path = './weibo_detail/{}.txt'.format(self.user_id)
        if not os.path.exists(weibo_comments_save_path):
              os.makedirs(os.path.dirname(weibo_comments_save_path))`

如果爬取不同用户ID的微博内容，既不存在新的用户ID对应的.txt，Line 187中的if判断为True，则创建文件夹"./weibo.detail"时则会产生"文件夹已存在，无法创建错误"。

`       weibo_comments_save_path = './weibo_detail'
        weibo_comments_save_name = '/{}.txt'.format(self.user_id
        if not os.path.exists(weibo_comments_save_path):
              os.makedirs(os.path.dirname(weibo_comments_save_path))
         with open(os.path.join(weibo_comments_save_path, weibo_comments_save_name), 'w+') as f: `
这样会不会更好一些？

**Comment by jinfagang** [comment]
Haven't test multi id crawl, if you get error then you can edit it to the right and submit PR to me, I will merge your request.

**Comment by zixuanweeei** [comment]
I have submitted a PR. But I didn't mean multi-ID crawling. The problem is that when the directory "weibo_detail" exists, some error by "os.makedirs" will be throw. Maybe you can got it refering to my PR. Thank you. @jinfagang

**Comment by HaipingLIU** [comment]
The same problem with u @zixuanweeei

**Comment by jinfagang** [comment]
Got your PR, thanks for contribution, I will merge it tonight.
