### ISSUE TITLE
WinError 5 Access is denied

### ISSUE THREAD

**Issue by luisxxx** [jinfagang/weibo_terminater#42]
![permission](https://cloud.githubusercontent.com/assets/15872969/26174979/1a969dfa-3b1f-11e7-954d-4bfa4dd5e5e9.jpg)

Hello, I run this project in my win 10 system, it did not work. The problem is shown in the figure above.
I also tried in another win7 system and encountered the same question. The python versions are 3.5.3 and 3.6.1. Neither of them worked. What is more, I run the Command Prompt as an **_administrator_** not as a common user.
Thanks

**Comment by jinfagang** [comment]
For permission issue, most probilistic by sudo, if on windows you should run as administrater.

**Comment by luisxxx** [comment]
I did run as administrator on windows but it still did not work.
However, I tried ubuntu virtual machine and it worked.  I could put it aside for some time.
Thanks.
