### ISSUE TITLE
Could not save file

### ISSUE THREAD

**Issue by luisxxx** [jinfagang/weibo_terminater#44]
Hello,  here are two difference examples which I cannot save a file.
_ubuntu virtual machine ubuntu-16.04.2-desktop-amd64, python 3.5.2_
**_1_ with weibo_detail folder**
when I try the command: _**sudo python3 main -i 5979819802**_
I failed to get all the data and save file _**if I had not deleted**_ the _weibo_detail_ folder, as indicated in the following figure.
![sb2 xrw8 e n n8vgqb](https://cloud.githubusercontent.com/assets/15872969/26226916/26ec3fd6-3bfd-11e7-9ca9-132823437a57.png)
**_2_ without weibo_detail folder**
when I try the command: _**sudo python3 main -i 5979819802**_
I failed to get all the data and save file **_if I had deleted_** the _weibo_detail_ folder, as indicated in the following figure.
![4mjrqltnw3ct0 ruy5c0b h](https://cloud.githubusercontent.com/assets/15872969/26227129/6c9a23e4-3bfe-11e7-892a-f0a3ef4c5d89.png)

I have no idea what to do with it although I also referred a few closed issues.
Thanks for your efforts!

**Comment by jinfagang** [comment]
If you want save file, check the work flow version

**Comment by luisxxx** [comment]
Thank you, I will check that.
