### ISSUE TITLE
命令行输入“python3 main.py -i realangelababy”后，显示“python3不是内部或外部命令”

### ISSUE THREAD

**Issue by tianqingfish** [jinfagang/weibo_terminater#45]
Python版本是3.6.1,
操作系统是windows x64，是在当前路径下的命令行下运行的。
还有一个关于phantomjs路径配置问题：
Windows下的路径是这样的：G:\weibo_terminater\phantomjs-2.1.1-windows\bin\phantomjs.exe
而mac系统路径斜杠是反向的（config.py文件默认的是/），很困惑，还请解答一下，多谢了~

**Comment by jinfagang** [comment]
If you are using Windows, better set Python path first, strongly recommended using Anaconda on Windows platform.
