### ISSUE TITLE
不加代理IP,很快就会被BAN吧?

### ISSUE THREAD

**Issue by xiaosimao** [jinfagang/weibo_terminater#8]
我一个帐号,一个ID的数据还没跑完,已经显示被封,不知道作者用了多少帐号,爬了多久?爬了多少数据?

**Comment by xiyouMc** [comment]
这个作者有点骗star。 鉴定完毕 而且有类似的项目  SinaSpider 。

**Comment by jinfagang** [comment]
First, this project inferenced other repo, but not completely copy and paste, if you said I am cheated, I am going ask you, am I copy that? That repo is based on python2.7 please. Second, I almost rebuild a scraper, the core of my project is not that one, if you don't like other project get star, you can write another, don't mess my place.
